Traceback (most recent call last):
  File "/home/aditya/kivy_venv/lib/python3.6/site-packages/kivy/lang/parser.py", line 471, in execute_directives
    mod = __import__(package)
ModuleNotFoundError: No module named 'classdefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./engine.py", line 64, in <module>
    myApp.run()
  File "/home/aditya/kivy_venv/lib/python3.6/site-packages/kivy/app.py", line 828, in run
    self.load_kv(filename=self.kv_file)
  File "/home/aditya/kivy_venv/lib/python3.6/site-packages/kivy/app.py", line 599, in load_kv
    root = Builder.load_file(rfilename)
  File "/home/aditya/kivy_venv/lib/python3.6/site-packages/kivy/lang/builder.py", line 301, in load_file
    return self.load_string(data, **kwargs)
  File "/home/aditya/kivy_venv/lib/python3.6/site-packages/kivy/lang/builder.py", line 368, in load_string
    parser = Parser(content=string, filename=fn)
  File "/home/aditya/kivy_venv/lib/python3.6/site-packages/kivy/lang/parser.py", line 401, in __init__
    self.parse(content)
  File "/home/aditya/kivy_venv/lib/python3.6/site-packages/kivy/lang/parser.py", line 507, in parse
    self.execute_directives()
  File "/home/aditya/kivy_venv/lib/python3.6/site-packages/kivy/lang/parser.py", line 473, in execute_directives
    mod = __import__('.'.join(package.split('.')[:-1]))
ValueError: Empty module name
